# Generated by Django 5.0.7 on 2024-08-26 18:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_rename_user_post_author_remove_post_image_post_media'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='user',
            new_name='author',
        ),
    ]
