# Generated by Django 5.0.7 on 2024-08-26 19:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_rename_user_userprofile_author'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='author',
            new_name='user',
        ),
    ]
